2024-03-05 21:23:12,731 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:23:30,677 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:23:42,449 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:24:02,400 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:24:14,237 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:24:21,953 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:24:32,651 - /home/ssh_aayush/DoseDash/DoseDash/settings.py changed, reloading.
2024-03-05 21:24:41,277 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
2024-03-05 21:24:49,003 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
Traceback (most recent call last):
  File "/home/ssh_aayush/DoseDash/manage.py", line 22, in <module>
    main()
  File "/home/ssh_aayush/DoseDash/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django_crontab/crontab.py", line 126, in run_job
    job = self.__get_job_by_hash(job_hash)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssh_aayush/anaconda3/envs/DoseDash/lib/python3.11/site-packages/django_crontab/crontab.py", line 171, in __get_job_by_hash
    raise RuntimeError(
RuntimeError: No job with hash 7b09190693029d9b3412548ba6c6f5ec found. It seems the crontab is out of sync with your settings.CRONJOBS. Run "python manage.py crontab add" again to resolve this issue!
2024-03-05 21:25:18,345 - /home/ssh_aayush/DoseDash/DoseDash/settings.py changed, reloading.
2024-03-05 21:34:04,558 - /home/ssh_aayush/DoseDash/DoseDash/settings.py changed, reloading.
2024-03-05 21:34:11,225 - /home/ssh_aayush/DoseDash/DoseDash/settings.py changed, reloading.
2024-03-05 21:34:18,973 - /home/ssh_aayush/DoseDash/DoseDash/settings.py changed, reloading.
2024-03-05 21:36:20,730 - /home/ssh_aayush/DoseDash/dosedashapp/views.py changed, reloading.
